# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e84ad42c78be1b04482c0752a1d4ed659c9eee4ad3df730a5727701d9d3feb16efffe46fde6ae623dd044949dd41c99ee4469d0794d5a3e2ac1aa534a7b741f

test:
  secret_key_base: a6940e4af0c9b5ec1ea079af96a6dd7cf80ad54750af587efa4462618474b825095d599cc2c8df7beadce06983e05dcc2fc72b24ab362dd5548da6de5d5c8c33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
